const data = [
    // Novio
    { id: 1, url: 'CanoDiaz', invited: 'Familia Cano Diaz', tickets: '2', table: 'Plus' },
    { id: 2, url: 'CanoMeza', invited: 'Familia Cano Meza', tickets: '4', table: '1' },
    { id: 3, url: 'MejiaCano', invited: 'Familia Mejía Cano', tickets: '4', table: '1' },
    { id: 4, url: 'MejiaOrta', invited: 'Familia Mejía Orta', tickets: '3', table: '1' },
    { id: 5, url: 'RoldanCano', invited: 'Familia Roldan Cano', tickets: '5', table: '5' },
    { id: 6, url: 'CanoPalacios', invited: 'Familia Cano Palacios', tickets: '5', table: '3' },
    { id: 7, url: 'CanoLopez', invited: 'Familia Cano López', tickets: '4', table: '5' },
    { id: 8, url: 'CanoMendoza', invited: 'Familia Cano Mendoza', tickets: '4', table: '19' },
    { id: 9, url: 'CanoPerez', invited: 'Familia Cano Pérez', tickets: '4', table: '19' },
    { id: 10, url: 'CanoArguello', invited: 'Familia Cano Argüello', tickets: '3', table: '13' },
    { id: 11, url: 'AndreaMeza', invited: 'Tía Andrea Meza', tickets: '1', table: '11' },
    { id: 12, url: 'SergioMeza', invited: 'Tío Sergio Meza', tickets: '1', table: '25' },
    { id: 13, url: 'ChuchoMeza', invited: 'Tío Chucho', tickets: '1', table: '11' },
    { id: 14, url: 'LugoMeza', invited: 'Familia Lugo Meza', tickets: '4', table: '11' },
    { id: 15, url: 'RosaMeza', invited: 'Tía Rosa Meza', tickets: '2', table: '11' },
    { id: 16, url: 'MargaritaMeza', invited: 'Tía Margarita Meza', tickets: '2', table: '11' },
    { id: 17, url: 'MaryMeza', invited: 'Tía Mary Meza', tickets: '3', table: '25' },
    { id: 18, url: 'KarlaCano', invited: 'Karla Cano', tickets: '3', table: '19' },
    { id: 19, url: 'EnriqueOrtega', invited: 'Hno. Enrique Ortega', tickets: '2', table: '7' },
    { id: 20, url: 'DavidSilva', invited: 'Hno. David Silva', tickets: '1', table: '13' },
    { id: 21, url: 'BenjaminSilva', invited: 'Hno. Benjamín Silva', tickets: '1', table: '13' },
    { id: 22, url: 'HernandezVilla', invited: 'Familia Hernández Villa', tickets: '5', table: '7' },
    { id: 23, url: 'OrtegaGuerrero', invited: 'Familia Ortega Guerero', tickets: '4', table: '15' },
    { id: 24, url: 'OrtegaCampos', invited: 'Familia Ortega Campos', tickets: '5', table: '15' },
    { id: 25, url: 'OrtegaCarmona', invited: 'Familia Ortega Carmona', tickets: '3', table: '15' },
    { id: 26, url: 'Susy', invited: 'Hna. Susy', tickets: '1', table: '13' },
    { id: 27, url: 'GabyBarrios', invited: 'Hna. Gabriela Barrios', tickets: '2', table: '13' },
    { id: 28, url: 'JuanBarrios', invited: 'Hno. Juan Barrios', tickets: '1', table: '9' },
    { id: 30, url: 'RodriguezFlores', invited: 'Familia Rodríguez Flores', tickets: '3', table: '9' },
    { id: 31, url: 'PatyMonroy', invited: 'Hna. Paty Monroy', tickets: '2', table: '9' },
    { id: 32, url: 'GabyAbarca', invited: 'Gaby Abarca Monroy', tickets: '2', table: '9' },
    { id: 33, url: 'ElizabethMonroy', invited: 'Elizabeth Monroy', tickets: '2', table: '9' },
    { id: 34, url: 'CarlosSora', invited: 'Hnos. Carlos y Sora', tickets: '2', table: '7' },
    { id: 35, url: 'MendozaGalvez', invited: 'Familia Mendoza Gálvez', tickets: '2', table: '13' },
    { id: 36, url: 'AlexisMunguia', invited: 'Alexis Munguía', tickets: '1', table: '23' },
    { id: 37, url: 'CesarAlarcon', invited: 'Cesar Alarcón', tickets: '1', table: '23' },
    { id: 38, url: 'YabinMendoza', invited: 'Yabin Mendoza', tickets: '1', table: '23' },
    { id: 39, url: 'Brandon', invited: 'Brandon', tickets: '1', table: '23' },
    { id: 40, url: 'Alonso', invited: 'Alonso', tickets: '1', table: '23' },
    { id: 41, url: 'AlexisMosiños', invited: 'Alexis Mosiños', tickets: '1', table: '23' },
    { id: 42, url: 'FranciscoGarcia', invited: 'Francisco García', tickets: '2', table: '23' },
    { id: 43, url: 'SaulGutierrez', invited: 'Saul Gutiérrez', tickets: '2', table: '23' },
    { id: 44, url: 'Asael', invited: 'Asael', tickets: '1', table: '17' },
    { id: 45, url: 'Ismael', invited: 'Ismael', tickets: '1', table: '17' },
    { id: 46, url: 'AbrahamMeli', invited: 'Abraham y Meli', tickets: '2', table: '17' },
    { id: 47, url: 'OmarCorona', invited: 'Omar Corona', tickets: '1', table: '17' },
    { id: 48, url: 'Nelson', invited: 'Nelson', tickets: '1', table: '17' },
    { id: 49, url: 'MagdielMonse', invited: 'Magdiel y Monse', tickets: '2', table: '17' },
    { id: 50, url: 'JorgeTolentino', invited: 'Jorge Tolentino', tickets: '2', table: '21' },
    { id: 51, url: 'SebastianMontes', invited: 'Sebastian Montes', tickets: '1', table: '21' },
    { id: 52, url: 'RicardoZarate', invited: 'Ricardo Zarate', tickets: '1', table: '21' },
    { id: 53, url: 'AlbertoRojo', invited: 'Alberto Rojo', tickets: '2', table: '21' },
    { id: 54, url: 'Irving', invited: 'Irving', tickets: '1', table: '21' },
    { id: 57, url: 'Pati', invited: 'Patricia Veras', tickets: '1', table: '25' },
    { id: 59, url: 'TiaJamiz', invited: 'Tia Jamiz', tickets: '3', table: '25' },
    { id: 60, url: 'LuzDelCarmen', invited: 'Luz Del Carmen', tickets: '3', table: '3' },
    { id: 110, url: 'HnaCarmen', invited: 'Hna. Carmen Silva', tickets: '2', table: '25' },
    
    // Novia
    { id: 61, url: 'DiazGonzales', invited: 'Familia Díaz González', tickets: '3', table: '2' },
    { id: 62, url: 'BarajasContreras', invited: 'Familia Barajas Contreras', tickets: '2', table: '?' },
    { id: 63, url: 'TerceroGonzalez', invited: 'Familia Tercero González', tickets: '4', table: '6' },
    { id: 64, url: 'MarquezDiaz', invited: 'Familia Marquez Díaz', tickets: '5', table: '4' },
    { id: 65, url: 'TiaLiz', invited: 'Tia Liz', tickets: '2', table: '6' },
    { id: 67, url: 'GonzalezDiaz', invited: 'Familia Gonzalez Díaz', tickets: '1', table: '8' },
    { id: 68, url: 'TiaMaribel', invited: 'Tia Maribel', tickets: '5', table: '8' },
    { id: 69, url: 'HernandezJuarez', invited: 'Familia Hernández Juarez', tickets: '1', table: '6' },
    { id: 70, url: 'ContrerazSalasar', invited: 'Familia Contreraz Salasar', tickets: '4', table: '10' },
    { id: 71, url: 'Julia', invited: 'Hna. Julia', tickets: '2', table: '8' },
    { id: 72, url: 'SolRodriguez', invited: 'Hna. Sol Rodríguez', tickets: '3', table: '10' },
    { id: 73, url: 'Rosalva', invited: 'Hna. Rosalva', tickets: '1', table: '10' },
    { id: 74, url: 'Jazmin', invited: 'Hna. Jazmin', tickets: '2', table: '10' },
    { id: 75, url: 'GamalielFlores', invited: 'Hno. Gamaliel Flores', tickets: '4', table: '12' },
    { id: 76, url: 'CarmenMejia', invited: 'Hna. Carmen Mejía', tickets: '2', table: '18' },
    { id: 77, url: 'AngelReyes', invited: 'Hno. Angel Reyes', tickets: '4', table: '24' },
    { id: 78, url: 'Fransis', invited: 'Hna. Fransis', tickets: '2', table: '18' },
    { id: 79, url: 'HnoNemesio', invited: 'Hno. Nemesio', tickets: '4', table: '2' },
    { id: 80, url: 'HnaMagda', invited: 'Hna. Magda', tickets: '3', table: '16' },
    { id: 81, url: 'HnaClaudia', invited: 'Hna. Claudia', tickets: '7', table: '16' },
    { id: 82, url: 'HnaDalila', invited: 'Hna. Dalila', tickets: '3', table: '6' },
    { id: 83, url: 'HnaLupita', invited: 'Hna. Lupita', tickets: '2', table: '18' },
    { id: 84, url: 'HnoHiginio', invited: 'Hno. Higinio', tickets: '3', table: '12' },
    { id: 85, url: 'PastorRicardo', invited: 'Pastor Ricardo', tickets: '4', table: '12' },
    { id: 86, url: 'HnoRicardoFabela', invited: 'Familia Fabela Gonzalez', tickets: '2', table: '14' },
    { id: 87, url: 'HnoJacobMondragon', invited: 'Hno. Jacob Mondragon', tickets: '4', table: '14' },
    { id: 88, url: 'FamPatronEncarnacion', invited: 'Familia Patron Encarnación', tickets: '4', table: '27' },
    { id: 89, url: 'MisaelMarlen', invited: 'Misael y Marlen', tickets: '2', table: '20' },
    { id: 90, url: 'Felipe', invited: 'Felipe', tickets: '3', table: '20' },
    { id: 91, url: 'Rutits', invited: 'Rutits', tickets: '1', table: '20' },
    { id: 92, url: 'RayMundo', invited: 'Ray Gonzalez', tickets: '3', table: '6' },
    { id: 93, url: 'Graciela', invited: 'Graciela Diaz', tickets: '5', table: '4' },
    { id: 94, url: 'Cami', invited: 'Cami', tickets: '3', table: '20' },
    { id: 95, url: 'EncarnacionFonseca', invited: 'Encarnación Fonseca', tickets: '4', table: '27' },
    { id: 96, url: 'BarronEncarnacion', invited: 'Barrón Encarnación', tickets: '2', table: '27' },
    { id: 97, url: 'SaraAlmanza', invited: 'Hna. Sara Almanza', tickets: '5', table: '14' },
    { id: 98, url: 'MariaDeJesusMaldonado', invited: 'Hna. María de Jesus Maldonado', tickets: '1', table: '18' },
    { id: 99, url: 'VickySergio', invited: 'Sra. Vicky y Sr. Sergio', tickets: '2', table: '8' },
    { id: 100, url: 'PerezMixtega', invited: 'Familia Pérez Mixtega', tickets: '5', table: '10' },
    { id: 101, url: 'Kimi', invited: 'Kimi', tickets: '4', table: '8' },
    { id: 102, url: 'TiaLupe', invited: 'Tia Lupe', tickets: '5', table: '4' },
    { id: 103, url: 'LeonelCampos', invited: 'Hno. Leonel Campos', tickets: '3', table: '33' },
    { id: 104, url: 'Estudiantina', invited: 'Estudiantina', tickets: '20', table: '18 y 20' },
    { id: 105, url: 'SilviaGarduño', invited: 'Hna. Silvia Garduño', tickets: '4', table: '12 y 14' },
    { id: 106, url: 'RobertoRodarte', invited: 'Hno. Roberto Rodarte', tickets: '2', table: '2' },
];

export default data;