const data = [
    // Novio
    { id: 1, url: 'CanoDiaz', invited: 'Familia Cano Diaz', tickets: '2', table: 'Plus' },
    { id: 2, url: 'CanoMeza', invited: 'Familia Cano Meza', tickets: '4', table: '?' },
    { id: 3, url: 'MejiaCano', invited: 'Familia Mejía Cano', tickets: '4', table: '?' },
    { id: 4, url: 'MejiaOrta', invited: 'Familia Mejía Orta', tickets: '2', table: '?' },
    { id: 5, url: 'RoldanCano', invited: 'Familia Roldan Cano', tickets: '6', table: '?' },
    { id: 6, url: 'CanoPalacios', invited: 'Familia Cano Palacios', tickets: '5', table: '?' },
    { id: 7, url: 'CanoLopez', invited: 'Familia Cano López', tickets: '4', table: '?' },
    { id: 8, url: 'CanoMendoza', invited: 'Familia Cano Mendoza', tickets: '4', table: '?' },
    { id: 9, url: 'Cano Perez', invited: 'Familia Cano Pérez', tickets: '4', table: '?' },
    { id: 10, url: 'CanoArguello', invited: 'Familia Cano Argüello', tickets: '3', table: '?' },
    { id: 11, url: 'AndreaMeza', invited: 'Tía Andrea Meza', tickets: '1', table: '?' },
    { id: 12, url: 'SergioMeza', invited: 'Tío Sergio Meza', tickets: '1', table: '?' },
    { id: 13, url: 'ChuchoMeza', invited: 'Tío Chucho', tickets: '1', table: '?' },
    { id: 14, url: 'AlejandraMeza', invited: 'Tía Alejandra Meza', tickets: '2', table: '?' },
    { id: 15, url: 'RosaMeza', invited: 'Tía Rosa Meza', tickets: '2', table: '?' },
    { id: 16, url: 'MargaritaMeza', invited: 'Tía Margarita Meza', tickets: '2', table: '?' },
    { id: 17, url: 'MaryMeza', invited: 'Tía Mary Meza', tickets: '3', table: '?' },
    { id: 18, url: 'KarlaCano', invited: 'Karla Cano', tickets: '3', table: '?' },
    { id: 19, url: 'EnriqueOrtega', invited: 'Hno. Enrique Ortega', tickets: '2', table: '?' },
    { id: 20, url: 'DavidSilva', invited: 'Hno. David Silva', tickets: '1', table: '?' },
    { id: 21, url: 'BenjaminSilva', invited: 'Hno. Benjamín Silva', tickets: '1', table: '?' },
    { id: 22, url: 'HernandezVilla', invited: 'Familia Hernández Villa', tickets: '5', table: '?' },
    { id: 23, url: 'OrtegaGuerrero', invited: 'Familia Ortega Guerero', tickets: '4', table: '?' },
    { id: 24, url: 'OrtegaCampos', invited: 'Familia Ortega Campos', tickets: '5', table: '?' },
    { id: 25, url: 'OrtegaCarmona', invited: 'Familia Ortega Carmona', tickets: '3', table: '?' },
    { id: 26, url: 'Susy', invited: 'Hna. Susy', tickets: '1', table: '?' },
    { id: 27, url: 'GabyBarrios', invited: 'Hna. Gabriela Barrios', tickets: '1', table: '?' },
    { id: 28, url: 'JuanBarrios', invited: 'Hno. Juan Barrios', tickets: '1', table: '?' },
    { id: 29, url: 'GloriaMancera', invited: 'Familia Gloria Mancera', tickets: '2', table: '?' },
    { id: 30, url: 'RodriguezFlores', invited: 'Familia Rodríguez Flores', tickets: '3', table: '?' },
    { id: 31, url: 'AbarcaMonroy', invited: 'Familia Abarca Monroy', tickets: '5', table: '?' },
    { id: 32, url: 'CarlosSora', invited: 'Hnos. Carlos y Sora', tickets: '2', table: '?' },
    { id: 33, url: 'Rachel', invited: 'Hna. Rachel', tickets: '1', table: '?' },
    { id: 34, url: 'MendozaGalvez', invited: 'Familia Mendoza Gálvez', tickets: '2', table: '?' },
    { id: 35, url: 'AlexisMunguia', invited: 'Alexis Munguía', tickets: '1', table: '?' },
    { id: 36, url: 'CesarAlarcon', invited: 'Cesar Alarcón', tickets: '1', table: '?' },
    { id: 37, url: 'YabinMendoza', invited: 'Yabin Mendoza', tickets: '1', table: '?' },
    { id: 38, url: 'JosefinaSilva', invited: 'Josefina Silva', tickets: '1', table: '?' },
    { id: 39, url: 'SharysCoronel', invited: 'Sharys Coronel', tickets: '1', table: '?' },
    { id: 40, url: 'Alonso', invited: 'Alonso', tickets: '1', table: '?' },
    { id: 41, url: 'AlexisMosiños', invited: 'Alexis Mosiños', tickets: '1', table: '?' },
    { id: 42, url: 'FranciscoGarcia', invited: 'Francisco García', tickets: '1', table: '?' },
    { id: 43, url: 'SaulGutierrez', invited: 'Saul Gutiérrez', tickets: '1', table: '?' },
    { id: 44, url: 'Asael', invited: 'Asael', tickets: '1', table: '?' },
    { id: 45, url: 'Ismael', invited: 'Ismael', tickets: '1', table: '?' },
    { id: 46, url: 'AbrahamMeli', invited: 'Abraham y Meli', tickets: '2', table: '?' },
    { id: 47, url: 'OmarCorona', invited: 'Omar Corona', tickets: '1', table: '?' },
    { id: 48, url: 'NelsonMagdiel', invited: 'Nelson y Magdiel', tickets: '2', table: '?' },
    { id: 49, url: 'JorgeTolentino', invited: 'Jorge Tolentino', tickets: '1', table: '?' },
    { id: 50, url: 'SebastianMontes', invited: 'Sebastian Montes', tickets: '1', table: '?' },
    { id: 51, url: 'RicardoZarate', invited: 'Ricardo Zarate', tickets: '1', table: '?' },
    { id: 52, url: 'AlbertoRojo', invited: 'Alberto Rojo', tickets: '1', table: '?' },
    { id: 53, url: 'Irving', invited: 'Irving', tickets: '1', table: '?' },
    { id: 54, url: 'GiovanniPerea', invited: 'Giovanni Perea', tickets: '1', table: '?' },
    { id: 55, url: 'GustavoPicazo', invited: 'Gustavo Picazo', tickets: '2', table: '?' },
    { id: 56, url: 'BrunoRomán', invited: 'Bruno Román', tickets: '1', table: '?' },
];

export default data;